import type { EntradaMetrado } from "@/lib/sicc/types"
import { OBRA_DEMO } from "@/lib/sicc/demo-obra"

export const ENTRADAS_METRADO_DEMO: EntradaMetrado[] = [
  {
    id: "met-001",
    rubroId: 5,
    fecha: "2026-02-08",
    cantidad: 35,
    frente: "Cárcamo EB Severino",
    observaciones: "Limpieza subacuática sector A",
    registradoPor: OBRA_DEMO.residente,
  },
  {
    id: "met-002",
    rubroId: 14,
    fecha: "2026-02-10",
    cantidad: 850,
    frente: "Compuerta Peniche",
    observaciones: "Replanteo frente sur",
    registradoPor: OBRA_DEMO.residente,
  },
  {
    id: "met-003",
    rubroId: 15,
    fecha: "2026-02-10",
    cantidad: 620,
    frente: "Compuerta Peniche",
    registradoPor: OBRA_DEMO.residente,
  },
  {
    id: "met-004",
    rubroId: 16,
    fecha: "2026-02-10",
    cantidad: 280,
    frente: "Compuerta Peniche",
    observaciones: "Excavación sector norte",
    registradoPor: OBRA_DEMO.residente,
  },
  {
    id: "met-005",
    rubroId: 16,
    fecha: "2026-02-11",
    cantidad: 195,
    frente: "Compuerta Peniche",
    registradoPor: OBRA_DEMO.residente,
  },
  {
    id: "met-006",
    rubroId: 17,
    fecha: "2026-02-11",
    cantidad: 420,
    frente: "Compuerta Peniche",
    observaciones: "Colocación escollera talud provisional",
    registradoPor: OBRA_DEMO.residente,
  },
  {
    id: "met-007",
    rubroId: 26,
    fecha: "2026-02-12",
    cantidad: 180,
    frente: "Compuerta Ciénega",
    observaciones: "Relleno compactado capa 1",
    registradoPor: OBRA_DEMO.residente,
  },
  {
    id: "met-008",
    rubroId: 8,
    fecha: "2026-02-12",
    cantidad: 45,
    frente: "Acceso Poza Honda",
    registradoPor: OBRA_DEMO.residente,
  },
]
